#!/usr/bin/env bash
# This script traps SIGTERM and displays a message

trap "echo 'I am invincible!!!'" SIGTERM

# Keep the script running so it can receive the signal
while true
do
    sleep 1
done
